ferreteria/urls.py
#from django.conf.urls import url
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from app.views import *
from app.Views.productoView import *
from app.Views.presentacionView import *
from app.Views.precioView import *
from app.Views.aperturacajaView import *
from app.Views.cierrecajaView import *
from app.Views.operacionView import *
from app.Views.pedidoView import *
from app.Views.usuarioView import *
from app.Views.clienteView import *
from app.Views.rutaView import *
from app.Views.visitaView import *
from app.Views.errorView import *

from app.Views.ventaView import *

from app.Views.loteView import *
 
from app.Views.reporteView import *
###########################################################
#   Usuario: Erick Sulca, Ulises Bejar
#   Fecha: 05/06/18
#   Última modificación:
#   Descripción: url registrarError
###########################################################

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home, name='Home'),
    path('login/', Login, name='Login'),
    path('logout/', Logout, name='Logout'),
    path('prueba/', Prueba, name='prueba'),

    ################## Caja #######################
    path('Caja/imprimir/', imprimir_prueba, name='imprimir_caja'),
    path('Caja/apertura/', registrarAperturacaja, name='apertura_caja'),
    path('Caja/cierre/', registrarCierrecaja, name='cierre_caja'),
    path('Caja/operacion/', registrarOperacion, name='operacion_caja'),
    path('Caja/operacion/detalle/<int:id_operacion>', detalleOperacion, name='operaciones_detalle'),
    path('Caja/operaciones/listar', listarOperacions, name='operaciones_listar'),

    ################## Venta #######################

    path('Venta/nuevo/', nuevoVenta,name="venta_nuevo"),
    path('Venta/listar/', ListarVentas, name="venta_listar"),
    path('Venta/imprimir/<int:venta_id>/', ImprimirVenta, name="venta_imprimir"),
    path('Venta/detalle/<int:venta_id>/', detalle_Venta, name ='venta_detalle'),

    #path('Venta/nuevo/', registrarPedido, name='registrar_venta'),
    # path('venta/listar/<int:<producto_buscado>\d+)/<int:<dni>\d+)/<int:<fecha_ini>[0-9]{2}-?[0-9]{2}-?[0-9]{4})/<int:<fecha_f>[0-9]{2}-?[0-9]{2}-?[0-9]{4})/', Fentas),
    # path('venta/listar/<int:<producto_buscado>\d+)/<int:<dni>\d+)/', Fentas),
    #
    # path('venta/listar/<int:<producto_buscado>)/$', Fentas,name="listar_productoid"),
    # path('venta/listar/<int:<dni>\d+)/$', Fentas),
    # path('venta/listar/<int:<fecha_ini>[0-9]{2}-?[0-9]{2}-?[0-9]{4})/<int:<fecha_f>[0-9]{2}-?[0-9]{2}-?[0-9]{4})/$', Fentas),
    # path('venta/listar/<int:<fecha_f>[0-9]{2}-?[0-9]{2}-?[0-9]{4})/$', Fentas),
    path('Venta/filtrar/', filterVentas, name = "filtra_ventas"),
    #path('venta/listar/<int:<producto>\d+)$', FiltrarVentas.as_view, name="filtra_ventas"),
    #path('Producto/detalle/<int:<producto_id>\d+)/$', detalleProducto),
    #path('Producto/editar/<int:<producto_id>\d+)/$', editarProducto),

    ################## Producto #######################
    path('Producto/listar/', ListarProductos, name ='listar_producto'),
    path('Producto/nuevo/', registrarProducto, name ='registrar_producto'),
    path('Producto/detalle/<int:producto_id>/', detalleProducto, name ='ver_producto'),
    path('Producto/editar/<int:producto_id>/', editarProducto, name ='editar_producto'),
    path('Producto/eliminar/<int:pk>/', eliminar_producto, name='eliminar_producto'),

    ################## Catalogo #######################
    #path('Presentacion/registrar/', registrarPresentacionProducto, name ='registrar_presentacion'),
    #path('Presentacion/eliminar/<int:presentacion_id>/<int:producto_id>/', eliminarPresentacionProducto, name ='eliminar_presentacion'),
    #path('Presentacion/getPresentaciones/', getPresentaciones, name ='get_presentacion'),
#
    #path('Precios/getPrecios/', getPrecios, name ='get_precios'),
    #path('pruebaExcel/', IngresarPrecios),

    ################## Cliente #######################
    path('Cliente/nuevo/', nuevoCliente, name='nuevo_cliente'),
    path('Cliente/detalle/<int:cliente_id>/', detalleCliente, name='detalle_cliente'),
    path('Cliente/editar/<int:cliente_id>/', editarCliente, name='editar_cliente'),
    path('Cliente/listar/', listarCliente, name='listar_cliente'),
    #path('Cliente/buscar/', IngresarPrecios),
    path('Cliente/actualizar/', IngresarPrecios, name='actualiza_cliente'),
    path('Cliente/eliminar/<int:pk>/', eliminar_cliente, name='eliminar_cliente'),
    
    ################## Lote #######################
    path('Lote/nuevo/', nuevoLote, name='nuevo_lote'),
    path('Lote/listar/', listarLote, name='listar_lote'),
    path('Lote/detalle/<int:lote_id>/', detalleLote, name ='ver_lote'),
    ################## Pedidos #######################

    path('Pedido/nuevo/', registrarPedido),
    path('Pedido/listar/', ListarPedidos),
    path('Pedido/resumen/', ResumenPedidos),
    path('Pedido/detalle/<int:pedido_id>/', DetallePedido),
    path('Pedido/editar/<int:pedido_id>/', editarPedido),
    path('Pedido/eliminar/<int:pedido_id>/', eliminarPedido),
    path('Pedido/actualizar/', IngresarPrecios),
    path('Pedido/reporte/', IngresarPrecios),
    path('Pedido/buscar/', IngresarPrecios),
    path('Pedido/imprimir/', IngresarPrecios),

    ################## APP Movil #######################

    path('usuario/validar/', validarUsuario),
    path('usuario/ruta/', rutaUsuario),
    path('usuario/visita/cancelar/', cancelarVisita),
    path('usuario/visita/reiniciar/', reiniciarVisita),

    path('cliente/buscar/', buscarCliente),
    path('cliente/detalle/', detalleClienteWS),

    path('pedido/insertar/', InstarPedido),
    path('pedido/listar/', ListarPedido),
    path('pedido/detalle/', DetallePedidoMovil),
    path('pedido/editar/', DetallePedidoMovil),
    path('pedido/alerta/listar/',Listar_PedidoAlertaView.as_view(),name = 'listar_pedidoalertas'),

    path('pago/nuevo/', IngresarPrecios),


    #path('producto/presentacion/listar/', ListarPresentacionesProducto),
    path('producto/buscar/', BuscarProducto, name='buscar_producto'),
    path('producto/json_listar/', get_Productos.as_view(), name='listar_productos'),
    path('producto/presentacion/listar/', get_PresentacionProducto.as_view()),
    path('producto/presentacion/cantidad/', CantidadPresentacionesProducto),
    path('presentacion/listar/', get_Presentaciones.as_view(), name ='listar_presentacion'),

    path('detalletipooperacion/lista/',get_detalleTipoOperacion.as_view(),name ='listar_detalletipooperacio'),

    path('venta/detalle/<int:id_venta>',detalleVenta, name='detalle_venta'),

    path('error/registrar/', registrarError),




    

    #####################################################

#######################Rutas##############################

    #path('Ruta/nuevo/$', nuevoVenta),
    #path('Ruta/listar/$', ListarVenta),

#######################Información y Reportes##############################

    #path('Reporte/almacen/$', reporteAlmacen),
    path('Reporte/aperturascaja/', ReporteAperturasCaja, name="reporte_aperturascaja"),
    path('Reporte/venta/productos/', ReporteVentaProductos, name="reporte_venta_productos"),
    path('Reporte/ingreso/productos/', ReporteIngresoProductos, name="reporte_ingreso_productos"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals
 
from django.db import models
from django.contrib.auth.models import User
from django_resized import ResizedImageField

class Almacen(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)
    def __str__(self):
        return str(self.nombre)
    
class Caja(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)
    def __str__(self):
        return str(self.nombre)
    
class Aperturacaja(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=False)
    monto = models.FloatField()
    activo = models.BooleanField(blank=True,default=True)
    estado = models.BooleanField(blank=True,default=True)
    caja = models.ForeignKey(Caja, on_delete=models.CASCADE)

class Categoria(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)
    def __str__(self):
        return str(self.nombre)
    
class Cierrecaja(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    monto = models.FloatField()
    aperturacaja = models.ForeignKey(Aperturacaja, on_delete=models.CASCADE, related_name='apertura_cierrecaja')  # Field name made lowercase.
    validado = models.BooleanField(blank=True,default=True)
    descripcion = models.TextField(blank=True, null=True)
    estado = models.BooleanField(blank=True,default=True)

class Cliente(models.Model):
    nombre = models.CharField(max_length=45)
    direccion = models.CharField(max_length=45,blank=True, null=True)
    numerodocumento = models.CharField(max_length=11, blank=True, null=True)
    telefono = models.CharField(max_length=15,blank=True, null=True)
    imagen = ResizedImageField(size=[100, None],upload_to='clientes/', default="/imagen/default_cliente.jpg", blank=True, null=True)#upload_to='%Y/%m/%d',
    longitud = models.CharField(max_length=25, blank=True, null=True)
    latitud = models.CharField(max_length=25, blank=True, null=True)
    estado = models.BooleanField(blank=True,default=True)

    def __str__(self):
        return str(self.nombre)

class Cobro(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    monto = models.FloatField()
    estado = models.BooleanField(blank=True,default=True)
    venta = models.ForeignKey('Venta', on_delete=models.CASCADE)  # Field name made lowercase.
    #recibo = models.ForeignKey('Recibo', blank=True, null=True, on_delete=models.CASCADE)  # Field name made lowercase.

class Detalletipooperacion(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)
    tipooperacion = models.ForeignKey('Tipooperacion', on_delete=models.CASCADE)  # Field name made lowercase.
    def __str__(self):
        return self.nombre

class Lote(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    modificado = models.DateTimeField(auto_now=True, blank=True)
    proveedor = models.ForeignKey('Proveedor', on_delete=models.CASCADE)  # Field name made lowercase.
    nro_documento = models.CharField(max_length=45, blank=True, null=True)
    almacen = models.ForeignKey('Almacen', on_delete=models.CASCADE, blank=True,null=True)  # Field name made lowercase.
    monto = models.FloatField(blank=True, null=True)
    estado = models.BooleanField(blank=True,default=True)

    def __str__(self):
        str_return = 'Fecha : '+str(self.fecha) + ' - Monto S/. ' + str(self.monto)
        return str_return
    
class Operacion(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    monto = models.FloatField()
    descripcion = models.TextField(blank=True, null=True)
    aperturacaja = models.ForeignKey(Aperturacaja, on_delete=models.CASCADE, related_name='apertura_operacions')  # Field name made lowercase.
    detalletipooperacion = models.ForeignKey(Detalletipooperacion, on_delete=models.CASCADE)  # Field name made lowercase.
    venta = models.ForeignKey('Venta', blank=True, null=True, on_delete=models.CASCADE, related_name='venta_operacions')  # Field name made lowercase.
    lote = models.ForeignKey('Lote', blank=True, null=True, on_delete=models.CASCADE, related_name='lote_operacions')  # Field name made lowercase.
    estado = models.BooleanField(blank=True,default=True)
    def __str__(self):
        str_return = 'Fecha : '+str(self.fecha) + ' - Monto S/. ' + str(self.monto)
        return str_return
    
class Pedido(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    usuario = models.OneToOneField(User, on_delete= models.DO_NOTHING, related_name='usuario_pedidos', blank=True, null=True)
    cliente = models.ForeignKey(Cliente, blank=True, null=True, on_delete=models.CASCADE)  # Field name made lowercase.
    estado = models.BooleanField(blank=True,default=True)
    def __str__(self):
        return str(self.fecha)

class Empleado(models.Model):
    nombre = models.CharField(max_length=45)
    imei = models.CharField(max_length=45, blank=True, null=True)
    imagen = models.ImageField(blank=True, null=True)#upload_to='%Y/%m/%d',
    perfil = models.IntegerField(blank=True, null=True,default=1)
    estado = models.BooleanField(blank=True,default=True)

    def __str__(self):
        return str(self.nombre)
    
class Producto(models.Model):
    nombre = models.CharField(max_length=45)
    codigo = models.CharField(max_length=45, blank=True, null=True)
    cantidad = models.FloatField(default=0,blank=True, null=True)
    imagen = ResizedImageField(size=[100, None],upload_to='productos/', default="/imagen/default.jpg", blank=True, null=True)#upload_to='%Y/%m/%d',
    url = models.CharField(max_length=100, blank=True, null=True)
    valor = models.FloatField(default=1,blank=True)
    precio = models.FloatField(default=1,blank=True)
    estado = models.BooleanField(blank=True,default=True)

    def __str__(self):
        return str(self.nombre)
    
class Presentacion(models.Model):
    nombre = models.CharField(max_length=45)
    codigo = models.CharField(max_length=45, blank=True, null=True, unique=True)
    estado = models.BooleanField(blank=True,default=True)

    def __str__(self):
        return str(self.nombre)
    
class Producto_presentacions(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, related_name='producto_presentaciones')  # Field name made lowercase.
    presentacion = models.ForeignKey(Presentacion, on_delete=models.CASCADE)  # Field name made lowercase.
    precio_compra = models.FloatField(default=0,blank=True)
    precio_venta = models.FloatField(default=0,blank=True)
    valor = models.FloatField(default=1,blank=True)
    favorito = models.BooleanField(blank=True,default=False)
    estado = models.BooleanField(blank=True,default=True)
    
    def __str__(self):
        str_producto_presentacions = 'Producto: '+self.producto.nombre+' | Presentación: '+self.presentacion.nombre
        return str(str_producto_presentacions)
    
class Pedido_productopresentacions(models.Model):
    cantidad = models.FloatField(blank=True,null=True)
    producto_presentacions = models.ForeignKey(Producto_presentacions, on_delete=models.CASCADE)  # Field name made lowercase.
    pedido = models.ForeignKey(Pedido, on_delete=models.DO_NOTHING, related_name='pedido_presentacions')
    precio_pedido = models.FloatField(default=0,blank=True)
    #fecha_caducidad = models.DateTimeField(null=True, blank=True)
    estado = models.BooleanField(blank=True,default=True)
    def __str__(self):
        str_pedido_productos = 'Producto: '+self.producto_presentacions.producto.nombre+' | Presentación: '+self.producto_presentacions.presentacion.nombre
        return str(str_pedido_productos)

class Lote_productopresentacions(models.Model):
    cantidad = models.FloatField(blank=True,null=True)
    cnt_cantidad = models.FloatField(blank=True,null=True) # descuento respectoa ventas 
    producto_presentacions = models.ForeignKey(Producto_presentacions, on_delete=models.CASCADE)  # Field name made lowercase.
    precio_lote = models.FloatField(default=0,blank=True, )
    lote = models.ForeignKey(Lote, on_delete=models.DO_NOTHING, related_name="lote_presentacions")
    fecha_caducidad = models.DateTimeField(null=True, blank=True)
    estado = models.BooleanField(blank=True,default=True)
    def __str__(self):
        str_lote_productos = 'Producto: '+self.producto_presentacions.producto.nombre+' | Presentación: '+self.producto_presentacions.presentacion.nombre
        return str(str_lote_productos)

    # FUNCION CANTIDAD CONTAR_STOCK() ON
class Producto_categorias(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)  # Field name made lowercase.
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)  # Field name made lowercase.

class Proveedor(models.Model):
    nombre = models.CharField(max_length=45)
    direccion = models.CharField(max_length=45)
    documento = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)

    def __str__(self):
        return str(self.nombre)

class Tipo_recibo(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)

class Tipooperacion(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)

app/templates/cliente/detalle.html
{% extends "base.html" %}
{% block imports %}

	<script >

			var marker;  //variable de marcador


			var a= parseFloat('{{oCliente.latitud}}');
			var b= parseFloat('{{oCliente.longitud}}');


			$( document ).ready(function() {
				console.log( "ready!" );
		});

	function initMap() {
			//const var1= -13.1680054;
			//const var2= -74.221639;
			var uluru = {lat: a, lng: b};

			var map = new google.maps.Map(document.getElementById('map'), {
				zoom: 10,
				center: uluru
			});
			var marker = new google.maps.Marker({
				position: uluru,
				map: map
			});
		}


	</script>
{% endblock %}

{% block title %}
Información de Cliente
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
		<h3 class="box-title">Detalle de Cliente</h3>
        <div class="card-header-right">
            <ul class="list-unstyled card-option">
                <li><i class="fa fa fa-wrench open-card-option"></i></li>
                <li><i class="fa fa-window-maximize full-card"></i></li>
                <li><i class="fa fa-minus minimize-card"></i></li>
                <li><i class="fa fa-refresh reload-card"></i></li>
                <li><i class="fa fa-trash close-card"></i></li>
            </ul>
        </div>
    </div>
    <div class="card-block table-border-style">
        <div class="table-responsive">
            <div class="white-box">
                <h3 class="box-title">Datos de cliente</h3>
			<div>
				<table id="tCamiones"  class="table">
					<tr>
						<td>Nombre: </td>
						<td>{{ oCliente.nombre }}</td>
					</tr>
					<tr>
						<td>Dirección: </td>
						<td>{{ oCliente.direccion }}</td>
					</tr>
					<tr>
						<td>N° Documento: </td>
						<td>{{ oCliente.numerodocumento }}</td>
					</tr>
					<tr>
						<td>Ubicación: </td>
						<td>{{ oCliente.longitud }} - {{ oCliente.longitud }}</td>
					</tr>
			</div>
			</div>

	    </div>
		<label for="id_latitud">My Google Maps Demo</label><br>
		<div id="map" style="position: relative;overflow: hidden;height: 300px;">
		<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA94LBsliF6TX_7XT76lfJAopVP_h2RkkU&callback=initMap">
									</script>
    </div>
</div>
{% endblock %}

app/templates/cliente/editar.html
<!-- Usuario: Erick sulca
	 fecha: 01/06/18
	 última modificación: 12/06/18
	 Descripción: se agrego la función getMapa, y toggleBounce para hacer más dinámico el marcador del mapa -->

{% extends "base.html" %}

{% block imports %}
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css" integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossorigin=""/>

<!-- Make sure you put this AFTER Leaflet's CSS -->
<script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo=" crossorigin=""></script>
{% endblock %}

{% block title %}
Editar Cliente
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
        <div class="card-header-right">
            <ul class="list-unstyled card-option">
                <li><i class="fa fa fa-wrench open-card-option"></i></li>
                <li><i class="fa fa-window-maximize full-card"></i></li>
                <li><i class="fa fa-minus minimize-card"></i></li>
                <li><i class="fa fa-refresh reload-card"></i></li>
                <li><i class="fa fa-trash close-card"></i></li>
            </ul>
        </div>
    </div>
    <div class="card-block table-border-style">
        <div class="table-responsive">
            <div class="white-box">
                <h3 class="box-title">Formulario de nuevo cliente</h3>
                <form action="." method="post" enctype="multipart/form-data">
					{% csrf_token %}
				<ul>

				{% load widget_tweaks %}
				{% csrf_token %}
					<div class="form-group">
				    {% for field in form %}
						{{ field.errors }}
						{{ field.label_tag }}</br>
						{{ field|add_class:"form-control" }}
				    {% endfor %}

				</ul>
				<ul>
					<hr>
					<div class="col-12  justify-content-center">
					<div id="mapid" style=" height: 400px;" class="justify-content-center"></div>
					</div>
					<button type="submit" class="btn btn-success">Actualizar</button>
				</ul>
				</form>
	    	</div>
	    </div>
    </div>
</div>
{% endblock %}
{% block footer  %}
<script type="text/javascript">
	$(document).ready(function() {
		var map ;
		var theMarker  = {};
		var time = 1;
		var coordenadas = [-12.6150756, -73.7913895]
		var map = L.map('mapid').setView(coordenadas, 16);
		L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
			maxZoom: 19,
			attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>',
			maxZoom: 18,
			id: 'mapbox/streets-v11',
			tileSize: 512,
			zoomOffset: -1,
			accessToken: 'pk.eyJ1IjoiZXJpaWNrIiwiYSI6ImNsajV5OTRhbTBnNnMzZ29yemFieXZidTIifQ.kCX-VyaXd_CF7d2GrbqYPQ'
		}).addTo(map);

		addCoords(coordenadas)

		console.log(theMarker)
		function onMapClick(e) {
			console.log(theMarker)
			//theMarker = new L.Marker(e.latlng, {draggable:true});
        	//map.addLayer(theMarker);
			coordenadas = e.latlng
			addCoords(coordenadas)
			$(id_latitud).val(coordenadas['lat'])
			$(id_longitud).val(coordenadas['lng'])
			//L.marker(e.latlng).addTo(map);
		}
		
		function addCoords(coordenadas){
			map.removeLayer(theMarker)
			theMarker = L.marker(coordenadas, {draggable:true});
        	map.addLayer(theMarker);
        	//L.marker(coordenadas).addTo(map);
		}

		map.on('click', onMapClick);
	});
</script>
{% endblock %}

app/templates/cliente/listar.html
{% extends "base.html" %}
{% block imports %}
	<script type="text/javascript">
		//evento click para boton editar
		$(document).on('Click', '.btn-editar', function(e){

			e.preventDefault();
			var row=$(this).paren().parent()[0];
			console.log(row);
		});
	</script>
{% endblock %}

{% block title %}
Clientes
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
		<h3 class="box-title">Lista de Clientes</h3>
        <div class="card-header-right">
            <ul class="list-unstyled card-option">
                <li><i class="fa fa fa-wrench open-card-option"></i></li>
                <li><i class="fa fa-window-maximize full-card"></i></li>
                <li><i class="fa fa-minus minimize-card"></i></li>
                <li><i class="fa fa-refresh reload-card"></i></li>
                <li><i class="fa fa-trash close-card"></i></li>
            </ul>
        </div>
    </div>
    <div class="card-block table-border-style">
        <div class="table-responsive">
            <div class="white-box">
				{% load widget_tweaks %}
				{% csrf_token %}
					<div class="form-group">
					<table id="tCamiones"  class="table">
						<thead>
	                        <tr>
	                            <th>#</th>
	                            <th>Nombre</th>
	                            <th>Dirección</th>
	                            <th>N° Documento</th>
	                            <th>Opciones</th>
	                        </tr>
	                    </thead>
				    {% for oCliente in oClientes %}
				    <tr>
				    	<td>{{ forloop.counter }}</td>
				    	<td>{{oCliente.nombre}}</td>
				    	<td>{{oCliente.direccion}}</td>
				    	<td>{{oCliente.numerodocumento}}</td>
				    	<td>
				    		<a href="/Cliente/detalle/{{oCliente.id}}/"><button type="button" class="btn btn-info">Ver</button> </a>
				    		<a href="/Cliente/editar/{{oCliente.id}}/"><button type="button" class="btn btn-primary">Editar</button></a>
				    	</td>
				    </tr>

				    {% endfor %}

					</table>
						<br>
						<div class="pagination" style="text-align: center;">
								<div class="pages">
										<ul>
											{% if oClientes.has_previous %}
													<li><a href="?page={{oClientes.previous_page_number}}"><<</a></li>
											{% endif %}
										</ul>
										<ul>
										{% for pg in page_range %}
												{% if oClientes.number == pg %}
														<li><a href="?page={{pg}}" class="btn btn-default">{{pg}}</a></li>
												{% else %}
														<li><a href="?page={{pg}}" class="btn">{{pg}}</a></li>
												{% endif %}
										{% endfor %}
										</ul>
										<ul>
											{% if oVenta.has_next %}
													<li><a href="?page={{oVenta.next_page_number}}">>></a></li>
											{% endif %}
										</ul>
								</div>
						</div>

				    <br>
	    			<a href="/Cliente/nuevo/"><button type="button" class="btn btn-success">Nuevo Cliente</button> </a>

			</div>
	    </div>
    </div>
</div>
{% endblock %}

app/templates/cliente/nuevo.html
<!-- Usuario: Erick sulca
	 fecha: 01/06/18
	 última modificación: 12/06/18
	 Descripción: se agrego la función getMapa, y toggleBounce para hacer más dinámico el marcador del mapa -->

{% extends "base.html" %}

{% block imports %}
{% endblock %}

{% block title %}
Registrar Nuevo Cliente
{% endblock %}

{% block content %}
<div class="card" id="app">
    <div class="card-header">
		<h3 class="box-title">Formulario nuevo Cliente</h3>
        <div class="card-header-right">
            <ul class="list-unstyled card-option">
                <li><i class="fa fa fa-wrench open-card-option"></i></li>
                <li><i class="fa fa-window-maximize full-card"></i></li>
                <li><i class="fa fa-minus minimize-card"></i></li>
                <li><i class="fa fa-refresh reload-card"></i></li>
                <li><i class="fa fa-trash close-card"></i></li>
            </ul>
        </div>
    </div>
    <div class="card-block table-border-style">
        <div class="table-responsive">
	    	<div class="white-box">
				<form action="." method="post" enctype="multipart/form-data">
					{% csrf_token %}
					{% load widget_tweaks %}
					<ul>
						<div class="form-group">
							{% for field in form %}
									{{ field.errors }}
									{{ field.label_tag }}</br>
									{{ field|add_class:"form-control" }}
							{% endfor %}
						</br>
					</ul>
					
					<ul>
						<button type="submit" class="btn btn-success">Agregar Cliente</button>
					</ul>
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block footer  %}

{% endblock %}