ferreteria/urls.py
#from django.conf.urls import url
from django.urls import path
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from app.views import *
from app.Views.productoView import *
from app.Views.presentacionView import *
from app.Views.precioView import *
from app.Views.aperturacajaView import *
from app.Views.cierrecajaView import *
from app.Views.operacionView import *
from app.Views.pedidoView import *
from app.Views.usuarioView import *
from app.Views.clienteView import *
from app.Views.rutaView import *
from app.Views.visitaView import *
from app.Views.errorView import *

from app.Views.ventaView import *

from app.Views.loteView import *
 
from app.Views.reporteView import *
###########################################################
#   Usuario: Erick Sulca, Ulises Bejar
#   Fecha: 05/06/18
#   Última modificación:
#   Descripción: url registrarError
###########################################################

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home, name='Home'),
    path('login/', Login, name='Login'),
    path('logout/', Logout, name='Logout'),
    path('prueba/', Prueba, name='prueba'),

    ################## Caja #######################
    path('Caja/imprimir/', imprimir_prueba, name='imprimir_caja'),
    path('Caja/apertura/', registrarAperturacaja, name='apertura_caja'),
    path('Caja/cierre/', registrarCierrecaja, name='cierre_caja'),
    path('Caja/operacion/', registrarOperacion, name='operacion_caja'),
    path('Caja/operacion/detalle/<int:id_operacion>', detalleOperacion, name='operaciones_detalle'),
    path('Caja/operaciones/listar', listarOperacions, name='operaciones_listar'),

    ################## Venta #######################

    path('Venta/nuevo/', nuevoVenta,name="venta_nuevo"),
    path('Venta/listar/', ListarVentas, name="venta_listar"),
    path('Venta/imprimir/<int:venta_id>/', ImprimirVenta, name="venta_imprimir"),
    path('Venta/detalle/<int:venta_id>/', detalle_Venta, name ='venta_detalle'),

    #path('Venta/nuevo/', registrarPedido, name='registrar_venta'),
    # path('venta/listar/<int:<producto_buscado>\d+)/<int:<dni>\d+)/<int:<fecha_ini>[0-9]{2}-?[0-9]{2}-?[0-9]{4})/<int:<fecha_f>[0-9]{2}-?[0-9]{2}-?[0-9]{4})/', Fentas),
    # path('venta/listar/<int:<producto_buscado>\d+)/<int:<dni>\d+)/', Fentas),
    #
    # path('venta/listar/<int:<producto_buscado>)/$', Fentas,name="listar_productoid"),
    # path('venta/listar/<int:<dni>\d+)/$', Fentas),
    # path('venta/listar/<int:<fecha_ini>[0-9]{2}-?[0-9]{2}-?[0-9]{4})/<int:<fecha_f>[0-9]{2}-?[0-9]{2}-?[0-9]{4})/$', Fentas),
    # path('venta/listar/<int:<fecha_f>[0-9]{2}-?[0-9]{2}-?[0-9]{4})/$', Fentas),
    path('Venta/filtrar/', filterVentas, name = "filtra_ventas"),
    #path('venta/listar/<int:<producto>\d+)$', FiltrarVentas.as_view, name="filtra_ventas"),
    #path('Producto/detalle/<int:<producto_id>\d+)/$', detalleProducto),
    #path('Producto/editar/<int:<producto_id>\d+)/$', editarProducto),

    ################## Producto #######################
    path('Producto/listar/', ListarProductos, name ='listar_producto'),
    path('Producto/nuevo/', registrarProducto, name ='registrar_producto'),
    path('Producto/detalle/<int:producto_id>/', detalleProducto, name ='ver_producto'),
    path('Producto/editar/<int:producto_id>/', editarProducto, name ='editar_producto'),
    path('Producto/eliminar/<int:pk>/', eliminar_producto, name='eliminar_producto'),

    ################## Catalogo #######################
    #path('Presentacion/registrar/', registrarPresentacionProducto, name ='registrar_presentacion'),
    #path('Presentacion/eliminar/<int:presentacion_id>/<int:producto_id>/', eliminarPresentacionProducto, name ='eliminar_presentacion'),
    #path('Presentacion/getPresentaciones/', getPresentaciones, name ='get_presentacion'),
#
    #path('Precios/getPrecios/', getPrecios, name ='get_precios'),
    #path('pruebaExcel/', IngresarPrecios),

    ################## Cliente #######################
    path('Cliente/nuevo/', nuevoCliente, name='nuevo_cliente'),
    path('Cliente/detalle/<int:cliente_id>/', detalleCliente, name='detalle_cliente'),
    path('Cliente/editar/<int:cliente_id>/', editarCliente, name='editar_cliente'),
    path('Cliente/listar/', listarCliente, name='listar_cliente'),
    #path('Cliente/buscar/', IngresarPrecios),
    path('Cliente/actualizar/', IngresarPrecios, name='actualiza_cliente'),
    path('Cliente/eliminar/<int:pk>/', eliminar_cliente, name='eliminar_cliente'),
    
    ################## Lote #######################
    path('Lote/nuevo/', nuevoLote, name='nuevo_lote'),
    path('Lote/listar/', listarLote, name='listar_lote'),
    path('Lote/detalle/<int:lote_id>/', detalleLote, name ='ver_lote'),
    ################## Pedidos #######################

    path('Pedido/nuevo/', registrarPedido),
    path('Pedido/listar/', ListarPedidos),
    path('Pedido/resumen/', ResumenPedidos),
    path('Pedido/detalle/<int:pedido_id>/', DetallePedido),
    path('Pedido/editar/<int:pedido_id>/', editarPedido),
    path('Pedido/eliminar/<int:pedido_id>/', eliminarPedido),
    path('Pedido/actualizar/', IngresarPrecios),
    path('Pedido/reporte/', IngresarPrecios),
    path('Pedido/buscar/', IngresarPrecios),
    path('Pedido/imprimir/', IngresarPrecios),

    ################## APP Movil #######################

    path('usuario/validar/', validarUsuario),
    path('usuario/ruta/', rutaUsuario),
    path('usuario/visita/cancelar/', cancelarVisita),
    path('usuario/visita/reiniciar/', reiniciarVisita),

    path('cliente/buscar/', buscarCliente),
    path('cliente/detalle/', detalleClienteWS),

    path('pedido/insertar/', InstarPedido),
    path('pedido/listar/', ListarPedido),
    path('pedido/detalle/', DetallePedidoMovil),
    path('pedido/editar/', DetallePedidoMovil),
    path('pedido/alerta/listar/',Listar_PedidoAlertaView.as_view(),name = 'listar_pedidoalertas'),

    path('pago/nuevo/', IngresarPrecios),


    #path('producto/presentacion/listar/', ListarPresentacionesProducto),
    path('producto/buscar/', BuscarProducto, name='buscar_producto'),
    path('producto/json_listar/', get_Productos.as_view(), name='listar_productos'),
    path('producto/presentacion/listar/', get_PresentacionProducto.as_view()),
    path('producto/presentacion/cantidad/', CantidadPresentacionesProducto),
    path('presentacion/listar/', get_Presentaciones.as_view(), name ='listar_presentacion'),

    path('detalletipooperacion/lista/',get_detalleTipoOperacion.as_view(),name ='listar_detalletipooperacio'),

    path('venta/detalle/<int:id_venta>',detalleVenta, name='detalle_venta'),

    path('error/registrar/', registrarError),




    

    #####################################################

#######################Rutas##############################

    #path('Ruta/nuevo/$', nuevoVenta),
    #path('Ruta/listar/$', ListarVenta),

#######################Información y Reportes##############################

    #path('Reporte/almacen/$', reporteAlmacen),
    path('Reporte/aperturascaja/', ReporteAperturasCaja, name="reporte_aperturascaja"),
    path('Reporte/venta/productos/', ReporteVentaProductos, name="reporte_venta_productos"),
    path('Reporte/ingreso/productos/', ReporteIngresoProductos, name="reporte_ingreso_productos"),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals
 
from django.db import models
from django.contrib.auth.models import User
from django_resized import ResizedImageField

class Almacen(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)
    def __str__(self):
        return str(self.nombre)
    
class Caja(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)
    def __str__(self):
        return str(self.nombre)
    
class Aperturacaja(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=False)
    monto = models.FloatField()
    activo = models.BooleanField(blank=True,default=True)
    estado = models.BooleanField(blank=True,default=True)
    caja = models.ForeignKey(Caja, on_delete=models.CASCADE)

class Categoria(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)
    def __str__(self):
        return str(self.nombre)
    
class Cierrecaja(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    monto = models.FloatField()
    aperturacaja = models.ForeignKey(Aperturacaja, on_delete=models.CASCADE, related_name='apertura_cierrecaja')  # Field name made lowercase.
    validado = models.BooleanField(blank=True,default=True)
    descripcion = models.TextField(blank=True, null=True)
    estado = models.BooleanField(blank=True,default=True)

class Cliente(models.Model):
    nombre = models.CharField(max_length=45)
    direccion = models.CharField(max_length=45,blank=True, null=True)
    numerodocumento = models.CharField(max_length=11, blank=True, null=True)
    telefono = models.CharField(max_length=15,blank=True, null=True)
    imagen = ResizedImageField(size=[100, None],upload_to='clientes/', default="/imagen/default_cliente.jpg", blank=True, null=True)#upload_to='%Y/%m/%d',
    longitud = models.CharField(max_length=25, blank=True, null=True)
    latitud = models.CharField(max_length=25, blank=True, null=True)
    estado = models.BooleanField(blank=True,default=True)

    def __str__(self):
        return str(self.nombre)

class Cobro(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    monto = models.FloatField()
    estado = models.BooleanField(blank=True,default=True)
    venta = models.ForeignKey('Venta', on_delete=models.CASCADE)  # Field name made lowercase.
    #recibo = models.ForeignKey('Recibo', blank=True, null=True, on_delete=models.CASCADE)  # Field name made lowercase.

class Detalletipooperacion(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)
    tipooperacion = models.ForeignKey('Tipooperacion', on_delete=models.CASCADE)  # Field name made lowercase.
    def __str__(self):
        return self.nombre

class Lote(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    modificado = models.DateTimeField(auto_now=True, blank=True)
    proveedor = models.ForeignKey('Proveedor', on_delete=models.CASCADE)  # Field name made lowercase.
    nro_documento = models.CharField(max_length=45, blank=True, null=True)
    almacen = models.ForeignKey('Almacen', on_delete=models.CASCADE, blank=True,null=True)  # Field name made lowercase.
    monto = models.FloatField(blank=True, null=True)
    estado = models.BooleanField(blank=True,default=True)

    def __str__(self):
        str_return = 'Fecha : '+str(self.fecha) + ' - Monto S/. ' + str(self.monto)
        return str_return
    
class Operacion(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    monto = models.FloatField()
    descripcion = models.TextField(blank=True, null=True)
    aperturacaja = models.ForeignKey(Aperturacaja, on_delete=models.CASCADE, related_name='apertura_operacions')  # Field name made lowercase.
    detalletipooperacion = models.ForeignKey(Detalletipooperacion, on_delete=models.CASCADE)  # Field name made lowercase.
    venta = models.ForeignKey('Venta', blank=True, null=True, on_delete=models.CASCADE, related_name='venta_operacions')  # Field name made lowercase.
    lote = models.ForeignKey('Lote', blank=True, null=True, on_delete=models.CASCADE, related_name='lote_operacions')  # Field name made lowercase.
    estado = models.BooleanField(blank=True,default=True)
    def __str__(self):
        str_return = 'Fecha : '+str(self.fecha) + ' - Monto S/. ' + str(self.monto)
        return str_return
    
class Pedido(models.Model):
    fecha = models.DateTimeField(auto_now_add=True, blank=True)
    usuario = models.OneToOneField(User, on_delete= models.DO_NOTHING, related_name='usuario_pedidos', blank=True, null=True)
    cliente = models.ForeignKey(Cliente, blank=True, null=True, on_delete=models.CASCADE)  # Field name made lowercase.
    estado = models.BooleanField(blank=True,default=True)
    def __str__(self):
        return str(self.fecha)

class Empleado(models.Model):
    nombre = models.CharField(max_length=45)
    imei = models.CharField(max_length=45, blank=True, null=True)
    imagen = models.ImageField(blank=True, null=True)#upload_to='%Y/%m/%d',
    perfil = models.IntegerField(blank=True, null=True,default=1)
    estado = models.BooleanField(blank=True,default=True)

    def __str__(self):
        return str(self.nombre)
    
class Producto(models.Model):
    nombre = models.CharField(max_length=45)
    codigo = models.CharField(max_length=45, blank=True, null=True)
    cantidad = models.FloatField(default=0,blank=True, null=True)
    imagen = ResizedImageField(size=[100, None],upload_to='productos/', default="/imagen/default.jpg", blank=True, null=True)#upload_to='%Y/%m/%d',
    url = models.CharField(max_length=100, blank=True, null=True)
    valor = models.FloatField(default=1,blank=True)
    precio = models.FloatField(default=1,blank=True)
    estado = models.BooleanField(blank=True,default=True)

    def __str__(self):
        return str(self.nombre)
    
class Presentacion(models.Model):
    nombre = models.CharField(max_length=45)
    codigo = models.CharField(max_length=45, blank=True, null=True, unique=True)
    estado = models.BooleanField(blank=True,default=True)

    def __str__(self):
        return str(self.nombre)
    
class Producto_presentacions(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, related_name='producto_presentaciones')  # Field name made lowercase.
    presentacion = models.ForeignKey(Presentacion, on_delete=models.CASCADE)  # Field name made lowercase.
    precio_compra = models.FloatField(default=0,blank=True)
    precio_venta = models.FloatField(default=0,blank=True)
    valor = models.FloatField(default=1,blank=True)
    favorito = models.BooleanField(blank=True,default=False)
    estado = models.BooleanField(blank=True,default=True)
    
    def __str__(self):
        str_producto_presentacions = 'Producto: '+self.producto.nombre+' | Presentación: '+self.presentacion.nombre
        return str(str_producto_presentacions)
    
class Pedido_productopresentacions(models.Model):
    cantidad = models.FloatField(blank=True,null=True)
    producto_presentacions = models.ForeignKey(Producto_presentacions, on_delete=models.CASCADE)  # Field name made lowercase.
    pedido = models.ForeignKey(Pedido, on_delete=models.DO_NOTHING, related_name='pedido_presentacions')
    precio_pedido = models.FloatField(default=0,blank=True)
    #fecha_caducidad = models.DateTimeField(null=True, blank=True)
    estado = models.BooleanField(blank=True,default=True)
    def __str__(self):
        str_pedido_productos = 'Producto: '+self.producto_presentacions.producto.nombre+' | Presentación: '+self.producto_presentacions.presentacion.nombre
        return str(str_pedido_productos)

class Lote_productopresentacions(models.Model):
    cantidad = models.FloatField(blank=True,null=True)
    cnt_cantidad = models.FloatField(blank=True,null=True) # descuento respectoa ventas 
    producto_presentacions = models.ForeignKey(Producto_presentacions, on_delete=models.CASCADE)  # Field name made lowercase.
    precio_lote = models.FloatField(default=0,blank=True, )
    lote = models.ForeignKey(Lote, on_delete=models.DO_NOTHING, related_name="lote_presentacions")
    fecha_caducidad = models.DateTimeField(null=True, blank=True)
    estado = models.BooleanField(blank=True,default=True)
    def __str__(self):
        str_lote_productos = 'Producto: '+self.producto_presentacions.producto.nombre+' | Presentación: '+self.producto_presentacions.presentacion.nombre
        return str(str_lote_productos)

    # FUNCION CANTIDAD CONTAR_STOCK() ON
class Producto_categorias(models.Model):
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE)  # Field name made lowercase.
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)  # Field name made lowercase.

class Proveedor(models.Model):
    nombre = models.CharField(max_length=45)
    direccion = models.CharField(max_length=45)
    documento = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)

    def __str__(self):
        return str(self.nombre)

class Tipo_recibo(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)

class Tipooperacion(models.Model):
    nombre = models.CharField(max_length=45)
    estado = models.BooleanField(blank=True,default=True)

app/templates/caja/apertura.html
{% extends "base.html" %}
{% block imports %}
{% endblock %}

{% block title %}
Registrar Nuevo Producto
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
		<h3 class="box-title">Formulario de apertura de caja</h3>
        <div class="card-header-right">
            <ul class="list-unstyled card-option">
                <li><i class="fa fa fa-wrench open-card-option"></i></li>
                <li><i class="fa fa-window-maximize full-card"></i></li>
                <li><i class="fa fa-minus minimize-card"></i></li>
                <li><i class="fa fa-refresh reload-card"></i></li>
                <li><i class="fa fa-trash close-card"></i></li>
            </ul>
        </div>
    </div>
    <div class="card-block table-border-style">
        <div class="table-responsive">
            <div class="white-box">
                <form action="/Caja/apertura/" method="post" enctype="multipart/form-data"> 
				<ul>
				{% load widget_tweaks %}
				{% csrf_token %}
					<div class="form-group">
					<label for="">Seleccione una Caja</label></br>
				    <select class="form-control" id="cmbCaja" name="cmbCaja" required="">
				    	<option value=""> </option>
                        {% for caja in cajas %}
                            <option value="{{caja.id}}">
                            {{caja.nombre}}
                            </option>
                        {% endfor %}
                        </select><br>	
				    {% for field in form %}
							{{ field.errors }}
							{{ field.label_tag }}</br>
							{{ field|add_class:"form-control" }}
				    {% endfor %}

					<button class="btn btn-success" data-toggle="modal" data-target="#agrearPresentacion">Aperturar Caja</button>


				</ul>
				</form>
 
			</div>
	    </div>
    </div>  
</div>
{% endblock %}

app/templates/caja/aperturaNoRegistrada.html
{% extends "base.html" %}
{% block imports %}
{% endblock %}

{% block title %}
Registrar Nuevo Producto
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
		<h3 class="box-title">Formulario de cierre de caja</h3>
        <div class="card-header-right">
            <ul class="list-unstyled card-option">
                <li><i class="fa fa fa-wrench open-card-option"></i></li>
                <li><i class="fa fa-window-maximize full-card"></i></li>
                <li><i class="fa fa-minus minimize-card"></i></li>
                <li><i class="fa fa-refresh reload-card"></i></li>
                <li><i class="fa fa-trash close-card"></i></li>
            </ul>
        </div>
    </div>
    <div class="card-block table-border-style">
        <div class="table-responsive">
            <div class="white-box">
                <h3 class="box-title">La caja: "{{Aperturacaja.caja.nombre}}" <b>no se encuentra aperturada</b></h3>
                
			</div>
	    </div>
    </div>  
</div>  
{% endblock %}

app/templates/caja/aperturaRegistrada.html
{% extends "base.html" %}
{% block imports %}
Registrar Nuevo Producto
{% endblock %}

{% block title %}
Registrar Nuevo Producto
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
        <h3 class="box-title">Formulario de apertura de caja</h3>
        <div class="card-header-right">
            <ul class="list-unstyled card-option">
                <li><i class="fa fa fa-wrench open-card-option"></i></li>
                <li><i class="fa fa-window-maximize full-card"></i></li>
                <li><i class="fa fa-minus minimize-card"></i></li>
                <li><i class="fa fa-refresh reload-card"></i></li>
                <li><i class="fa fa-trash close-card"></i></li>
            </ul>
        </div>
    </div>
    <div class="card-block table-border-style">
        <div class="table-responsive">
            <div class="white-box">
                <h3 class="box-title">La caja: "{{Aperturacaja.caja.nombre}}" ya se encuntra aperturada</h3>
                
			</div>
	    </div>
    </div>  
</div>  
{% endblock %}

app/templates/caja/cierre.html
{% extends "base.html" %}
{% block imports %}
<script src="https://cdn.jsdelivr.net/npm/vue@2"></script>
{% endblock %}

{% block title %}
Registrar Cierre de Caja
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
		<h3 class="box-title">Formulario de cierre de caja</h3>
        <div class="card-header-right">
            <ul class="list-unstyled card-option">
                <li><i class="fa fa fa-wrench open-card-option"></i></li>
                <li><i class="fa fa-window-maximize full-card"></i></li>
                <li><i class="fa fa-minus minimize-card"></i></li>
                <li><i class="fa fa-refresh reload-card"></i></li>
                <li><i class="fa fa-trash close-card"></i></li>
            </ul>
        </div>
    </div>
    <div class="card-block table-border-style">
        <div class="table-responsive">
            <div class="white-box">
                <form action="." method="post" enctype="multipart/form-data"> 
				<ul>
				{% load widget_tweaks %}
				{% csrf_token %}
					<div class="form-group" id="app">
						<label for="">Fecha de la apertura de Caja</label><br>
						<input type="text" name="fechaApertura" id="fechaApertura" required="" class="form-control" value="28 de agosto de 2023 a las 20:34" readonly="readonly">
						<input type="number" name="idApertura" id="idApertura" class="form-control" value="{{oAperturacaja.id}}" style="visibility: hidden" readonly="readonly">
						
								
						<label for="id_monto">Monto:</label><br>
						<input type="number"  value="{{oMontoCierre|stringformat:".2f"}}" name="monto"  step=".01" class="form-control" required="" id="monto" :readonly="bool_validado" >
						
						<div v-show="!bool_validado" >
							<label for="id_descripcion">Descripcion:</label><br>
							<textarea name="descripcion" cols="40" rows="10" class="form-control" id="id_descripcion"></textarea>
						</div>
				
						
						<label for="id_validado">Validado:</label>
						<input type="checkbox" name="validado" class="form-control fill" id="id_validado" checked="" v-model="bool_validado">
						
						<hr>
	
						<button class="btn btn-success" data-toggle="modal" data-target="#agrearPresentacion">Cerrar Caja</button>
					</div>
				</ul>
				</form>
 
			</div>
	    </div>
    </div>  
</div>  
{% endblock %}

{% block footer  %}

<script type="text/javascript">
    new Vue({
        delimiters: ['[[', ']]'],
        el: '#app',
        computed: {
            
        },
        created() {
        },
        data:   {
			bool_validado:true,
		},
		watch:{
			bool_validado: function(val){
				if(this.bool_validado == false){

				}
			},
		},
		methods: {

		},
	});
</script>
{% endblock %}

app/templates/caja/cierreNoRegistrado.html
{% extends "base.html" %}
{% block imports %}
Registrar Nuevo Producto
{% endblock %}

{% block title %}
Registrar Nuevo Producto
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
        <h3 class="box-title">Formulario de cierre de caja</h3>
        <div class="card-header-right">
            <ul class="list-unstyled card-option">
                <li><i class="fa fa fa-wrench open-card-option"></i></li>
                <li><i class="fa fa-window-maximize full-card"></i></li>
                <li><i class="fa fa-minus minimize-card"></i></li>
                <li><i class="fa fa-refresh reload-card"></i></li>
                <li><i class="fa fa-trash close-card"></i></li>
            </ul>
        </div>
    </div>
    <div class="card-block table-border-style">
        <div class="table-responsive">
            <div class="white-box">
                <h3 class="box-title">La caja <b>ya se encuentra cerrada</b></h3>
                
			</div>
	    </div>
    </div>  
</div>  
{% endblock %}

app/templates/caja/cierreRegistrado.html
{% extends "base.html" %}
{% block imports %}
{% endblock %}

{% block title %}
Cierre Registrado
{% endblock %}

{% block content %}
<div class="card">
    <div class="card-header">
		<h3 class="box-title"></h3>
        <div class="card-header-right">
            <ul class="list-unstyled card-option">
                <li><i class="fa fa fa-wrench open-card-option"></i></li>
                <li><i class="fa fa-window-maximize full-card"></i></li>
                <li><i class="fa fa-minus minimize-card"></i></li>
                <li><i class="fa fa-refresh reload-card"></i></li>
                <li><i class="fa fa-trash close-card"></i></li>
            </ul>
        </div>
    </div>
    <div class="card-block table-border-style">
        <div class="table-responsive">
            <div class="white-box">
                <h4 class="box-title">La caja ya se encuntra cerrada</h4>
                
			</div>
	    </div>
    </div>  
</div>  
{% endblock %}

app/templates/caja/imprimir.html
<html>
    <head>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.js"></script>
        <script src="https://printjs-4de6.kxcdn.com/print.min.js"></script>
          

        <link href="https://printjs-4de6.kxcdn.com/print.min.css" rel="stylesheet">   
        <style>
            /* style sheet for "A4" printing */
           /* A4 Landscape*/
            @page {
                size: A4 landscape;
                margin: 10%;
            }

            @media print {
            body {
                width: 20px;
                height:40px
            }
            /* etc */
}
        </style>
    </head>
    <body>
        <div id="print-area" class="print-main" style="width: 300;">
            <table>
                <tr>
                    <th>Name</th>
                    <th>Age</th>
                </tr>
                <tr>
                    <td>AAA</td>
                    <td>25</td>
                </tr>
                <tr>
                    <td>BBB</td>
                    <td>24</td>
                </tr>
            </table>
        </div>
        <button id="btnPrint">Print</button>

        <button type="button" onclick="printJS('http://127.0.0.1:8000/media/pdf/prueba_printPDF.pdf')">
            Print PDF
        </button>
        <script>
            $(document).ready(function(){
                $("#btnPrint").on("click",function(){
                    printJS({
                        maxWidth: 300,
                        type: 'html',
                        printable: 'print-area',
                        //type: 'html'
                    });
                })
            })
        </script>
    </body>
</html>